import type { Fixture } from '../../src/types/fixture';

export const FALLBACK_WEEK_1_MATCHES: Fixture[] = [
  {
    id: 'm1',
    week: 1,
    date: '2026-08-07',
    time: '18:30',
    status: 'played',
    homeTeam: { id: 101, name: 'BOLUSPOR', logo: 'https://file.mackolikfeeds.com/teams/101?w=s' },
    awayTeam: { id: 102, name: 'MANİSA FK', logo: 'https://file.mackolikfeeds.com/teams/102?w=s' },
    homeScore: 1,
    awayScore: 2,
    halfTimeHomeScore: 1,
    halfTimeAwayScore: 2,
  },
  {
    id: 'm2',
    week: 1,
    date: '2026-08-08',
    time: '14:00',
    status: 'played',
    homeTeam: { id: 103, name: 'BANDIRMASPOR', logo: 'https://file.mackolikfeeds.com/teams/103?w=s' },
    awayTeam: { id: 104, name: 'İSTANBULSPOR', logo: 'https://file.mackolikfeeds.com/teams/104?w=s' },
    homeScore: 3,
    awayScore: 0,
    halfTimeHomeScore: 2,
    halfTimeAwayScore: 0,
  },
  {
    id: 'm3',
    week: 1,
    date: '2026-08-08',
    time: '16:00',
    status: 'played',
    homeTeam: { id: 105, name: 'ÜMRANİYESPOR', logo: 'https://file.mackolikfeeds.com/teams/105?w=s' },
    awayTeam: { id: 106, name: 'MARDİN 1969 SPOR', logo: 'https://file.mackolikfeeds.com/teams/106?w=s' },
    homeScore: 0,
    awayScore: 0,
    halfTimeHomeScore: 0,
    halfTimeAwayScore: 0,
  },
  {
    id: 'm4',
    week: 1,
    date: '2026-08-08',
    time: '16:00',
    status: 'played',
    homeTeam: { id: 107, name: 'SİVASSPOR', logo: 'https://file.mackolikfeeds.com/teams/107?w=s' },
    awayTeam: { id: 108, name: 'ESENLER EROKSPOR', logo: 'https://file.mackolikfeeds.com/teams/108?w=s' },
    homeScore: 0,
    awayScore: 0,
    halfTimeHomeScore: 0,
    halfTimeAwayScore: 0,
  },
  {
    id: 'm5',
    week: 1,
    date: '2026-08-08',
    time: '18:30',
    status: 'played',
    homeTeam: { id: 109, name: 'ANTALYASPOR', logo: 'https://file.mackolikfeeds.com/teams/109?w=s' },
    awayTeam: { id: 110, name: 'KEÇİÖRENGÜCÜ', logo: 'https://file.mackolikfeeds.com/teams/110?w=s' },
    homeScore: 4,
    awayScore: 3,
    halfTimeHomeScore: 1,
    halfTimeAwayScore: 0,
  },
  {
    id: 'm6',
    week: 1,
    date: '2026-08-09',
    time: '16:00',
    status: 'played',
    homeTeam: { id: 111, name: 'IĞDIR FK', logo: 'https://file.mackolikfeeds.com/teams/111?w=s' },
    awayTeam: { id: 112, name: 'F. KARAGÜMRÜK', logo: 'https://file.mackolikfeeds.com/teams/112?w=s' },
    homeScore: 2,
    awayScore: 0,
    halfTimeHomeScore: 1,
    halfTimeAwayScore: 0,
  },
  {
    id: 'm7',
    week: 1,
    date: '2026-08-09',
    time: '16:00',
    status: 'played',
    homeTeam: { id: 113, name: 'SARIYER', logo: 'https://file.mackolikfeeds.com/teams/113?w=s' },
    awayTeam: { id: 114, name: 'MUĞLASPOR', logo: 'https://file.mackolikfeeds.com/teams/114?w=s' },
    homeScore: 2,
    awayScore: 0,
    halfTimeHomeScore: 1,
    halfTimeAwayScore: 0,
  },
  {
    id: 'm8',
    week: 1,
    date: '2026-08-09',
    time: '18:30',
    status: 'played',
    homeTeam: { id: 115, name: 'VANSPOR FK', logo: 'https://file.mackolikfeeds.com/teams/115?w=s' },
    awayTeam: { id: 116, name: 'KAYSERİSPOR', logo: 'https://file.mackolikfeeds.com/teams/116?w=s' },
    homeScore: 0,
    awayScore: 2,
    halfTimeHomeScore: 0,
    halfTimeAwayScore: 1,
  },
  {
    id: 'm9',
    week: 1,
    date: '2026-08-09',
    time: '18:30',
    status: 'played',
    homeTeam: { id: 117, name: 'BODRUM FK', logo: 'https://file.mackolikfeeds.com/teams/117?w=s' },
    awayTeam: { id: 118, name: 'BURSASPOR', logo: 'https://file.mackolikfeeds.com/teams/118?w=s' },
    homeScore: 0,
    awayScore: 2,
    halfTimeHomeScore: 0,
    halfTimeAwayScore: 2,
  },
  {
    id: 'm10',
    week: 1,
    date: '2026-08-10',
    time: '18:30',
    status: 'fixture',
    homeTeam: { id: 119, name: 'PENDİKSPOR', logo: 'https://file.mackolikfeeds.com/teams/119?w=s' },
    awayTeam: { id: 120, name: 'BATMAN PETROLSPOR', logo: 'https://file.mackolikfeeds.com/teams/120?w=s' },
    homeScore: null,
    awayScore: null,
    halfTimeHomeScore: null,
    halfTimeAwayScore: null,
  },
];
